### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by damianlluch** [RealTong/learn-nextjs-14#1]
Do you have any idea how to create an _app.tsx file in NextJS14 ? I haven't found a document and I need to define a provider for web3-react.js ?

Thanks

**Comment by RealTong** [comment]
In NextJS 14, both `App route` and `page route` are supported, and the entry files are `page.tsx` and `_app.tsx` respectively.

If you use the App route, then the new `page.tsx` and `layout.tsx` in the `app` folder are equivalent to `_app.tsx`.

If you are using the Page route, then it is the same as in NextJS 13.
